config, initramfs, Makefile:
config: Compress kernel with XZ, disable initramfs compression
config: Enable deep idle, set some other options
initramfs: Enable deep idle in sysfs upon startup
initramfs: Cleanup scripts in /sbin
initramfs: Add Voodoo extensions to install liblights and clean sdcard

diff --git a/build/initramfs/sbin/callboost b/build/initramfs/sbin/callboost
--- a/build/initramfs/sbin/callboost
+++ b/build/initramfs/sbin/callboost
@@ -1,6 +1,5 @@
 #!/system/bin/sh
 echo "In-call boost settings manager"
-echo ""
 
 BOOST_RCV_PATH=/sys/devices/virtual/misc/voodoo_sound/incall_boost_rcv
 BOOST_BT_PATH=/sys/devices/virtual/misc/voodoo_sound/incall_boost_bt
@@ -8,68 +7,81 @@ BOOST_SPK_PATH=/sys/devices/virtual/misc/voodoo_sound/incall_boost_spk
 BOOST_HP_PATH=/sys/devices/virtual/misc/voodoo_sound/incall_boost_hp
 INITSCRIPT_PATH=/system/etc/init.d/91callboost
 
-show_options()
-{
-echo "Usage: callboost [OPTION]"
-echo "Valid options:"
-echo ""
-echo "  enable    Set custom boost settings"
-echo "            Install boot script"
-echo "  disable   Remove boot script"
-echo "            Reset boost settings to defaults"
-echo "  show      Show current status"
-echo ""
-echo "Example: callboost show"
-echo ""
+show_options() {
+echo "
+Usage: callboost [OPTION]
+Valid options:
+
+  enable    Set custom boost settings
+            Install boot script
+  disable   Remove boot script
+            Reset boost settings to defaults
+  show      Show current status
+
+Example: callboost show
+"
 }
 
-show_status()
-{
-echo "Current settings:"
-echo ""
-echo "	RCV	BT	SPK	HP"
-echo "	$BOOST_RCV	$BOOST_BT	$BOOST_HP	$BOOST_SPK"
-echo ""
-echo "    0: +0dB, 1: +6dB, 2: +12dB, 3: +18dB"
-echo ""
+show_status() {
+echo "
+Displaying current settings:
+
+	RCV	BT	SPK	HP
+	$BOOST_RCV	$BOOST_BT	$BOOST_SPK	$BOOST_HP
+
+    0: +0dB, 1: +6dB, 2: +12dB, 3: +18dB
+"
 }
 
-write_initscript()
-{
-echo "#!/system/bin/sh" > $5
-echo "if  [ -e $BOOST_RCV_PATH ] &&
-    [ -e $BOOST_BT_PATH ] &&
-    [ -e $BOOST_SPK_PATH ] &&
-    [ -e $BOOST_HP_PATH ]; then" >> $5
-echo "echo $1 > $BOOST_RCV_PATH" >> $5
-echo "echo $2 > $BOOST_BT_PATH" >> $5
-echo "echo $3 > $BOOST_SPK_PATH" >> $5
-echo "echo $4 > $BOOST_HP_PATH" >> $5
-echo "fi" >> $5
-chown 0:0 $5
-chmod 755 $5
+boost_probe() {
+test -f $BOOST_RCV_PATH && test -e $BOOST_BT_PATH && test -e $BOOST_SPK_PATH && test -e $BOOST_HP_PATH
 }
 
-mount_system_rw()
-{
-mount -o rw,remount /system /system
+initscript_probe() {
+test -f $INITSCRIPT_PATH
 }
 
-mount_system_ro()
-{
-mount -o ro,remount /system /system
+read_boost() {
+BOOST_RCV=`cat $BOOST_RCV_PATH`
+BOOST_BT=`cat $BOOST_BT_PATH`
+BOOST_SPK=`cat $BOOST_SPK_PATH`
+BOOST_HP=`cat $BOOST_HP_PATH`
 }
 
+set_boost() {
+echo $1 > $BOOST_RCV_PATH
+echo $2 > $BOOST_BT_PATH
+echo $3 > $BOOST_SPK_PATH
+echo $4 > $BOOST_HP_PATH
+}
+
+write_initscript() {
+echo "#!/system/bin/sh
 if  [ -e $BOOST_RCV_PATH ] && [ -e $BOOST_BT_PATH ] && [ -e $BOOST_SPK_PATH ] && [ -e $BOOST_HP_PATH ]; then
-	BOOST_RCV=`cat $BOOST_RCV_PATH`
-	BOOST_BT=`cat $BOOST_BT_PATH`
-	BOOST_SPK=`cat $BOOST_SPK_PATH`
-	BOOST_HP=`cat $BOOST_HP_PATH`
+echo $BOOST_RCV > $BOOST_RCV_PATH
+echo $BOOST_BT > $BOOST_BT_PATH
+echo $BOOST_SPK > $BOOST_SPK_PATH
+echo $BOOST_HP > $BOOST_HP_PATH
+fi" > $INITSCRIPT_PATH
+chown 0.0 $INITSCRIPT_PATH
+chmod 755 $INITSCRIPT_PATH
+}
+
+mount_system_rw() {
+busybox mount -o rw,remount /system
+}
+
+mount_system_ro() {
+busybox mount -o ro,remount /system
+}
+
+if boost_probe; then
+	read_boost
 	if [ $1 ]; then
 		if [ $1 == "enable" ]; then
 			show_status
 
-			echo "Recommended: 1 or 2, 0, 0, 0"
+			echo "    Recommended: 1 or 2, 0, 0, 0"
 			echo ""
 			echo -n "    New RECEIVER boost value:	"
 			read BOOST_RCV
@@ -81,39 +93,27 @@ if  [ -e $BOOST_RCV_PATH ] && [ -e $BOOST_BT_PATH ] && [ -e $BOOST_SPK_PATH ] &&
 			read BOOST_HP
 			echo ""
 
-			mount_system_rw
-			write_initscript $BOOST_RCV $BOOST_BT $BOOST_SPK $BOOST_HP $INITSCRIPT_PATH
-			mount_system_ro
-			echo "Boot script installed."
+			( set_boost $BOOST_RCV $BOOST_BT $BOOST_SPK $BOOST_HP && echo "In-call boost values set." ) || ( echo "In-call boost values could not be set!" && exit )
 
-			$INITSCRIPT_PATH
-			echo "In-call boost values set."
+			( mount_system_rw && write_initscript && mount_system_ro && echo "Boot script installed." ) || ( echo "Boot script could not be installed!" && exit )
 
-			echo ""
 			show_status
 		elif [ $1 == "disable" ]; then
-			echo 0 > $BOOST_RCV_PATH
-			echo 0 > $BOOST_BT_PATH
-			echo 0 > $BOOST_SPK_PATH
-			echo 0 > $BOOST_HP_PATH
-			echo "In-call boost values reset to defaults."
+			show_status
 
-			if [ -e $INITSCRIPT_PATH ]; then
-				mount_system_rw
-				rm $INITSCRIPT_PATH
-				mount_system_ro
-				echo "Boot script removed."
+			( set_boost 0 0 0 0 && echo "In-call boost values reset to 0." ) || ( echo "In-call boost values could not be reset!" && exit )
+
+			if initscript_probe; then
+				( mount_system_rw && rm $INITSCRIPT_PATH && mount_system_ro && echo "Boot script removed." ) || ( echo "Boot script could not be removed!" && exit )
 			else
 				echo "Boot script not found. No need to remove."
 			fi
 
-			echo ""
 			show_status
 		elif [ $1 == "show" ]; then
 			show_status
 		else
 			echo "Unrecognized option."
-			echo ""
 			show_options
 		fi
 	else
